#!/bin/bash

# Set this to where you cloned the hbase-runner repository:
HBASE_RUNNER_HOME="${HOME}/work/clojure/hbase-runner"


# You can probably leave the rest alone:
CLOJURE_DIR="${HBASE_RUNNER_HOME}/lib/java"
CP_JARS="${CLOJURE_DIR}/*"
CP="${CP_JARS}:${HBASE_RUNNER_HOME}/src"

# set -x
if [ -z "$1" ]; then 
  java -cp "${CP}" jline.ConsoleRunner clojure.lang.Repl
  #java -cp "${CP}" clojure.lang.Script hbase-repl.clj
else
  scriptname=$1
  java -cp "${CP}" clojure.lang.Script $scriptname -- $*
fi